// <auto-generated />
using System;
using BistAdvisor.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BistAdvisor.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260819111500_AddApplicationSettings")]
    partial class AddApplicationSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BistAdvisor.Domain.Entities.ApplicationSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("ApplicationSettings");
                });

            modelBuilder.Entity("BistAdvisor.Domain.Entities.BulletinItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BulletinId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("ConfidenceRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal?>("DailyChangeRate")
                        .HasColumnType("decimal(8,4)");

                    b.Property<decimal?>("LastPrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<string>("ReasonText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SignalType")
                        .HasColumnType("int");

                    b.Property<int>("StockId")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalScore")
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("Id");

                    b.HasIndex("BulletinId");

                    b.HasIndex("StockId");

                    b.ToTable("BulletinItems");
                });

            modelBuilder.Entity("BistAdvisor.Domain.Entities.DailyBulletin", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AlgorithmVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateOnly>("BulletinDate")
                        .HasColumnType("date");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("DailyBulletins");
                });

            modelBuilder.Entity("BistAdvisor.Domain.Entities.DataFetchLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InsertedRowCount")
                        .HasColumnType("int");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RetrievedRowCount")
                        .HasColumnType("int");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("StockId")
                        .HasColumnType("int");

                    b.Property<int>("UpdatedRowCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StockId");

                    b.ToTable("DataFetchLogs");
                });

            modelBuilder.Entity("BistAdvisor.Domain.Entities.IndicatorResult", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("AverageVolume20")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("BarTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal?>("BollingerLower")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("BollingerMiddle")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("BollingerUpper")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTimeOffset>("CalculatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal?>("Ema20")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("Ema50")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("Interval")
                        .HasColumnType("int");

                    b.Property<decimal?>("MacdHistogramValue")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("MacdSignalValue")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("MacdValue")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("RsiValue")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("StochasticD")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("StochasticK")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("StockId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StockId", "Interval", "BarTime")
                        .IsUnique();

                    b.ToTable("IndicatorResults");
                });

            modelBuilder.Entity("BistAdvisor.Domain.Entities.MarketDataRawLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RawResponse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestSymbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("RetryCount")
                        .HasColumnType("int");

                    b.Property<int?>("StockId")
                        .HasColumnType("int");

                    b.Property<bool>("WasSuccessful")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("StockId");

                    b.ToTable("MarketDataRawLogs");
                });

            modelBuilder.Entity("BistAdvisor.Domain.Entities.PriceBar", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("AdjustedClosePrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTimeOffset>("BarTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("ClosePrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DataSource")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("HighPrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("Interval")
                        .HasColumnType("int");

                    b.Property<decimal>("LowPrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("OpenPrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("StockId")
                        .HasColumnType("int");

                    b.Property<long>("Volume")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("StockId", "Interval", "BarTime")
                        .IsUnique();

                    b.ToTable("PriceBars");
                });

            modelBuilder.Entity("BistAdvisor.Domain.Entities.SignalChange", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AlgorithmVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ChangeReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("ChangeTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal?>("NewConfidenceRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("NewScore")
                        .HasColumnType("decimal(6,2)");

                    b.Property<int>("NewSignalType")
                        .HasColumnType("int");

                    b.Property<decimal?>("PreviousConfidenceRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("PreviousScore")
                        .HasColumnType("decimal(6,2)");

                    b.Property<int>("PreviousSignalType")
                        .HasColumnType("int");

                    b.Property<int>("StockId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StockId");

                    b.ToTable("SignalChanges");
                });

            modelBuilder.Entity("BistAdvisor.Domain.Entities.SignalSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AlgorithmVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset>("BarTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("BollingerScore")
                        .HasColumnType("int");

                    b.Property<decimal?>("ConfidenceRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("EmaScore")
                        .HasColumnType("int");

                    b.Property<string>("Explanation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Interval")
                        .HasColumnType("int");

                    b.Property<int?>("MacdScore")
                        .HasColumnType("int");

                    b.Property<int?>("RsiScore")
                        .HasColumnType("int");

                    b.Property<int>("SignalType")
                        .HasColumnType("int");

                    b.Property<int?>("StochasticScore")
                        .HasColumnType("int");

                    b.Property<int>("StockId")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalScore")
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("Id");

                    b.HasIndex("StockId");

                    b.ToTable("SignalSnapshots");
                });

            modelBuilder.Entity("BistAdvisor.Domain.Entities.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Market")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ProviderSymbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Sector")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Symbol")
                        .IsUnique();

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("BistAdvisor.Domain.Entities.BulletinItem", b =>
                {
                    b.HasOne("BistAdvisor.Domain.Entities.DailyBulletin", "Bulletin")
                        .WithMany("Items")
                        .HasForeignKey("BulletinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BistAdvisor.Domain.Entities.Stock", "Stock")
                        .WithMany()
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bulletin");

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("BistAdvisor.Domain.Entities.DataFetchLog", b =>
                {
                    b.HasOne("BistAdvisor.Domain.Entities.Stock", "Stock")
                        .WithMany()
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("BistAdvisor.Domain.Entities.IndicatorResult", b =>
                {
                    b.HasOne("BistAdvisor.Domain.Entities.Stock", "Stock")
                        .WithMany()
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("BistAdvisor.Domain.Entities.MarketDataRawLog", b =>
                {
                    b.HasOne("BistAdvisor.Domain.Entities.Stock", "Stock")
                        .WithMany()
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("BistAdvisor.Domain.Entities.PriceBar", b =>
                {
                    b.HasOne("BistAdvisor.Domain.Entities.Stock", "Stock")
                        .WithMany("PriceBars")
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("BistAdvisor.Domain.Entities.SignalChange", b =>
                {
                    b.HasOne("BistAdvisor.Domain.Entities.Stock", "Stock")
                        .WithMany()
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("BistAdvisor.Domain.Entities.SignalSnapshot", b =>
                {
                    b.HasOne("BistAdvisor.Domain.Entities.Stock", "Stock")
                        .WithMany()
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("BistAdvisor.Domain.Entities.DailyBulletin", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("BistAdvisor.Domain.Entities.Stock", b =>
                {
                    b.Navigation("PriceBars");
                });
#pragma warning restore 612, 618
        }
    }
}
